title: "Socorro Animal"
description: "Portal de resgate de animais"
markdown: kramdown
url: "https://ajudaanimal.github.io"
baseurl: "/alerta"

collections:
  ocorrencias:
    output: true
    permalink: /ocorrencias/:path/

defaults:
  - scope:
      path: ""
      type: "ocorrencias"
    values:
      layout: "ocorrencia"
