title: "Socorro Animal"
description: "Portal de resgate de animais"
markdown: kramdown
url: "https://ajudaanimal.github.io"
baseurl: "/alerta"
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

# Obriga o Jekyll a gerar a página mesmo que a hora pareça futura
future: true 

collections:
  ocorrencias:
    output: true
    permalink: /ocorrencia/:name/

defaults:
  - scope:
      path: ""
      type: "ocorrencias"
    values:
      layout: "ocorrencia"
