jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Jekyll Site
        env:
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          # Se o Jekyll correr via GitHub Pages standard, podes passar assim:
          bundle exec jekyll build
